# Generated by Django 4.0.4 on 2022-04-21 09:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='avatars'),
        ),
    ]
